# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OrienteeringCITY' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrienteeringCITY

pod ‘Firebase’
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Core'

end
